# This file is part of the OpenEye project.
# SPDX-License-Identifier: SHL-2.1

"""Build a deterministic, full-system GEMM DMA workload for the SV testbench."""

from __future__ import annotations

import argparse
import os
import random
from pathlib import Path

from open_eye.gemm_mapper import GemmMapper
from open_eye.layer_parameters import LayerParameters
from open_eye.open_eye_parameters import OpenEyeParameters


K = 32
N = 32
SEED = 20261003


class _Shape:
    def __init__(self, shape):
        self.shape = shape


class _GemmLayer:
    name = "gemm"
    input = _Shape([None, K])
    output = _Shape([None, N])
    kernel = _Shape([K, N])


def _write_hex(path: Path, values: list[int], width: int) -> None:
    digits = (width + 3) // 4
    mask = (1 << width) - 1
    with path.open("w", encoding="ascii") as output:
        for value in values:
            output.write(f"{value & mask:0{digits}x}\n")


def generate(output_dir: Path) -> dict[str, int]:
    output_dir.mkdir(parents=True, exist_ok=True)
    os.environ.update({
        "CLUSTER_COLUMNS": "2",
        "CLUSTER_ROWS": "2",
        "NUM_GLB_IACT": "3",
        "NUM_GLB_PSUM": "4",
        "NUM_GLB_WGHT": "3",
        "PARALLEL_MACS": "2",
        "QUANT_AMOUNT": "1024",
        "DATAFLOW": "output_stationary",
        "BRANCHES": "1",
        "BUFFER_WIDTH": "12",
        "RAM_CELLS": "32",
    })

    rng = random.Random(SEED)
    activations = [rng.randint(16, 31) for _ in range(K)]
    weights = [[rng.randint(16, 31) for _ in range(K)] for _ in range(N)]
    bias = [0] * N
    expected = [
        sum(weights[row][column] * activations[column] for column in range(K)) + bias[row]
        for row in range(N)
    ]

    params = OpenEyeParameters(serial=True)
    layer_params = LayerParameters([], _GemmLayer(), params, 0, 1)
    mapper = GemmMapper(params, layer_params, 0,
                        [activations, weights, bias], sparse_iacts=0, sparse_wghts=0)
    mapper.make_stream()
    stream = mapper.get_stream()

    # Serial stream order is the FPGA DMA contract: configuration, activations,
    # weights, zero bias, then quantization. No TensorFlow model is needed.
    dma_words = []
    for channel in range(5):
        dma_words.extend(int(word) for word in stream[channel])
    _write_hex(output_dir / "gemm_dma_input.hex", dma_words, 64)
    _write_hex(output_dir / "gemm_expected.hex", expected, 32)

    config = {
        "dma_word_count": len(dma_words),
        "output_count": len(expected),
        "outputs_per_cluster_column": layer_params.used_psum_per_PE,
        "cluster_columns": params.Clusters_X,
        "seed": SEED,
        "k": K,
        "n": N,
        "gemm_mode": layer_params.gemm_mode,
    }
    with (output_dir / "gemm_workload.svh").open("w", encoding="ascii") as output:
        output.write("// Generated by generate_gemm_workload.py; do not edit.\n")
        for name, value in config.items():
            if name in {"seed", "k", "n"}:
                continue
            output.write(f"`define GEMM_{name.upper()} {value}\n")
    return config


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output_dir", type=Path)
    args = parser.parse_args()
    config = generate(args.output_dir)
    print(f"Generated output-stationary GEMM K={config['k']} N={config['n']} seed={config['seed']}")
    print(f"DMA words={config['dma_word_count']}, expected outputs={config['output_count']}")


if __name__ == "__main__":
    main()
